import htmlminifier from 'html-minifier-terser';

export default eleventyConfig => {
    eleventyConfig.addTransform('html-minify', (content, path) => {
        if (path && path.endsWith('.html') && eleventyConfig.globalData.settings.isProduction) {
            return htmlminifier.minify(content, {
                collapseBooleanAttributes: true,
                collapseWhitespace: true,
                decodeEntities: true,
                includeAutoGeneratedTags: false,
                preventAttributesEscaping: true,
                removeComments: true,
                removeRedundantAttributes: true,
                removeScriptTypeAttributes: true,
                removeStyleLinkTypeAttributes: true,
                minifyCSS: true,
                minifyJS: true
            });
        }
        return content;
    });
};
